const mongoose = require('mongoose')

const chemistryData = new mongoose.Schema({
        Albumin:{
            type:Boolean
        },
        AlkalinePhosphatase:{
            type:Boolean
        },
        AltSGPT:{
            type:Boolean
        },
        Amylase:{
            type:Boolean
        },
        AstSGOT:{
            type:Boolean
        },
        BilirubinTotal:{
            type:Boolean
        },
        BilirubinDirect:{
            type:Boolean
        },
        Bun:{
            type:Boolean
        },
        Calcium:{
            type:Boolean
        },
        CarbonDioxide:{
            type:Boolean
        },
        Chloride:{
            type:Boolean
        },
        CreativeKinase:{
            type:Boolean
        },
        CKMB:{
            type:Boolean
        },
        Creatinine:{
            type:Boolean
        },
        Electrolytes:{
            type:Boolean
        },
        Ferritin:{
            type:Boolean
        },
        GlucoseFasting:{
            type:Boolean
        },
        GlucoseRandm:{
            type:Boolean
        },
        GlutamylTransferase:{
            type:Boolean
        },
        HepaticFunction:{
            type:Boolean
        },
        LDH:{
            type:Boolean
        },
        LipidPandel:{
            type:Boolean
        },
        Lipase:{
            type:Boolean
        },
        IronTotal:{
            type:Boolean
        },
        Oxygen:{
            type:Boolean
        },
        Phosphorus:{
            type:Boolean
        },
        Potassium:{
            type:Boolean
        },
        ProteinTotal:{
            type:Boolean
        },
        T3UPTAKE:{
            type:Boolean
        },
        T4TOTAL:{
            type:Boolean
        },
        Sodium:{
            type:Boolean
        },
        Triglycerides:{
            type:Boolean
        },
        TSH:{
            type:Boolean
        },
        UricAcid:{
            type:Boolean
        },
})

    const HaemotologyData = new mongoose.Schema({
        BloodFilmDifferential:{
            type:Boolean
        },
        BloodFilmMorphology:{
            type:Boolean
        },
        CBC:{
            type:Boolean
        },
        FactorAnalysis:{
            type:Boolean
        },
        Prothrombin:{
            type:Boolean
        },
        PTAPTT:{
            type:Boolean
        },
        Reticulocyte:{
            type:Boolean
        }
    })   
    const ImmunoHaematol= new mongoose.Schema({
       
            ABO:{
                type:Boolean
            },
            AutoImmuneCold:{
                type:Boolean
            },
            AutoImmuneWarm:{
                type:Boolean
            },
            BloodGroupABO:{
                type:Boolean
            },
            BloodGroupAntiBody:{
                type:Boolean
            },
            Coombs:{
                type:Boolean
            },
            PreNatal:{
                type:Boolean
            },
            RhHDN:{
                type:Boolean
            }
      
    })
    const MicroBiology = new mongoose.Schema({
        CultureSenstivity:{
            type:Boolean
        },
        CultureFungus:{
            type:Boolean
        }
    })
    const Immunoserology = new mongoose.Schema({
        AslO:{
            type:Boolean
        },
        Brucella:{
            type:Boolean
        },
        CRP:{
            type:Boolean
        },
        DAT:{
            type:Boolean
        },
        Pylori:{
            type:Boolean
        },
        HbsAG:{
            type:Boolean
        },
        HepatitisAnti:{
            type:Boolean
        },
        HIV:{
            type:Boolean
        },
        Infectious:{
            type:Boolean
        },
        Rheumatoid:{
            type:Boolean
        },
        Rubella:{
            type:Boolean
        },
        VDRL:{
            type:Boolean
        },
        WEILOX19:{
            type:Boolean
        },
        WEILOX2:{
            type:Boolean
        },
        WEILOXK:{
            type:Boolean
        },
        WIDAL:{
            type:Boolean
        }
    
    })
    const TherapeuticDrugs = new mongoose.Schema({
        Carbamazepine:{
            type:Boolean
        },
        Phenobarbital:{
            type:Boolean
        },
        ValproicAcid:{
            type:Boolean
        }
    })
   
    const Chemistry = new mongoose.Schema({
        RequestID:{
            type:Number
        },
        PatientUHID:{
            type:Number
        },
        firstName:{
            type:String
        },
        status:{
            type:String
        },
        test:{
            type:String
        },
        priority:{
            type:String
        },
        department:{
            type:String
        },
        doctorID:{
            type:Number
        },
        nationalIdNumber:{
            type:String
        },
        dateOfBirth:{
            type:Date
        },
        sex:{
            type:String
        },
        patientZopaSub:{
            type:String
        },
        hospital:{
            type:String
        },
        ward:{
            type:String
        },
        bedNo:{
            type:String
        },
        paymentPC:{
            type:Boolean
        },
        paymentPR:{
            type:Boolean
        },
        referralDate:{
            type:Date
        },
        dateCollected:{
            type:Date
        },
        collectorInitial:{
            type:String
        },
        PatientSurvey:{
            type:Boolean
        },
        PatientFree:{
            type:Boolean
        },
        physicianName:{
            type:String
        },
        signature:{
            type:String
        },
        opdReceiptNo:{
            type:String
        },
        DoctorID:{
            type:Number
        },
        priority:{
            type:String
        },
        chemistryData:chemistryData,
        HaemotologyData:HaemotologyData,
        ImmunoHaematol:ImmunoHaematol,
        MicroBiology:MicroBiology,
        Immunoserology:Immunoserology,
        TherapeuticDrugs:TherapeuticDrugs
    })

    const chemistry = mongoose.model("chemistry",Chemistry)

exports.chemistry = chemistry