const mongoose = require('mongoose')
const { boolean } = require('joi')

const result2 = mongoose.Schema({
        SN:{
            type:String
        },
        clientName:{
            type:String
        },
        clientNationalID:{
            type:String
        },
        age2:{
            type:String
        },
        sex:{
            type:String
        },
        initialTest2:{
            type:String
        },
        repeatTest2:{
            type:String
        },
        result2:{
            type:String
        }
})

const result1 = mongoose.Schema({
    SN:{
        type:String
    },
    clientName:{
        type:String
    },
    clientNationalID:{
        type:String
    },
    age:{
        type:String
    },
    sex:{
        type:String
    },
    initialTest:{
        type:String
    },
    repeatTest:{
        type:String
    },
    result:{
        type:String
    }
})

    const hblViral = mongoose.Schema({
        PatientUHID:{
            type:Number
        },
        priority:{
            type:String
        },
        department:{
            type:String
        },
        DoctorID:{
            type:Number
        },
        firstName:{
            type:String
        },
        nationalIdNumber:{
            type:String
        },
        dateOfBirth:{
            type:Date
        },
        healthFacility:{
            type:String
        },
        zoba:{
            type:String
        },
        subZoba:{
            type:String
        },
        villCity:{
            type:String
        },
        RequestID:{
            type:Number
        },
        requestedBy:{
            type:String
        },
        tele:{
            type:String
        },
        test:{
            type:String
        },
        specimenDate:{
            type:Date
        },
        priority:{
            type:String
        },
        NHLDate:{
            type:Date
        },
        status:{
            type:String
        },
        test:{
            type:String
        },
        goodCondition:{
            type:Boolean
        },
        inadequateCondition:{
            type:Boolean
        },
        result1:result1,
        result2:result2,

        reportBy:{
            type:String
        },
        referralDate:{
            type:Date
        },
        reportSig:{
            type:String
        },
        approveBy:{
            type:String
        },
        approveDate:{
            type:Date
        },
        approveSig:{
            type:String
        }
    })

    const HBLViral = new mongoose.model("hblviral",hblViral)
    exports.HBLViral = HBLViral