const Joi = require('joi')
const mongoose = require('mongoose')

    const staff = new mongoose.Schema({
        department:{
            type:String
    },
        staffType:{
            type:String,
            required:true
    }
})
    const basic = new mongoose.Schema({
        name:{
            type:String,
            required:true
            },
        fatherName:{
            type:String,
            required:true
        },
        grandFatherName:{
            type:String,
            required:true
        },
        militaryNo:{
            type:String,
            required:true
        },
        parentSpouse:{
            type:String,
            required:true
        },
        birthPlace:{
            type:String,
            required:true
        },
        birthDate:{
            type:Date,
            required:true
        },
        gender:{
            type:String,
            required:true
        },
        bloodGroup:{
            type:String,
            required:true
        },
        cardNumber:{
            type:String,
            required:true
        },
        nationality:{
            type:String,
            required:true
        },
        nationalIdNumber:{
            type:String,
            required:true
        },
        ethincity:{
            type:String,
            required:true
        },
        religion:{
            type:String,
            required:true
        },
        maritalStatus:{
            type:String,
            required:true
        }
})

    const contact = new mongoose.Schema({
        address:{
            type:String,
            required:true
        },
        zone:{
            type:String,
            required:true
        },
        subZone:{
            type:String,
            required:true
        },
        village:{
            type:String,
            required:true
        },
        homeNumber:{
            type:String,
            required:true
        },
        mobileNumber:{
            type:String,
            required:true
        },
        email:{
            type:String,
            required:true
        }
    })

    const highLevel = new mongoose.Schema({
        literacy:{
            type:String,
            required:true
        },
        grade:{
            type:String,
            required:true
        },
        award:{
            type:String,
            required:true
        },
        fieldStudy:{
            type:String,
            required:true
        },
        profession:{
            type:String,
            required:true
        }
    })

    const workStatus = new mongoose.Schema({
        jobTitle:{
            type:String,
            required:true
        },
        workPlace:{
            type:String,
            required:true
        },
        zone:{
            type:String,
            required:true
        },
        subZone:{
            type:String,
            required:true
        },
        startDate:{
            type:Date,
            required:true
        },
        endDate:{
            type:Date,
            required:true
        },
        monthlySalary:{
            type:String,
            required:true
        },
        employeeStatus:{
            type:String,
            required:true
        },
        employeeType:{
            type:String,
            require:true
        }
    })

    const specialTraining = new mongoose.Schema({
        startDate:{
            type:Date,
            required:true
        },
        endDate:{
            type:Date,
            required:true
        },
        trainingType:{
            type:String,
            required:true
        },
        trainingPlace:{
            type:String,
            required:true
        },
        trainingInstitute:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        award:{
            type:String,
            required:true
        }
    })
    const workExperience = new mongoose.Schema({
        workType:{
            type:String,
            required:true
        },
        startDate:{
            type:Date,
            required:true
        },
        endDate:{
            type:Date,
            required:true
        },
        position:{
            type:String,
            required:true
        },
        supervisor:{
            type:String,
            required:true
        },
        section:{
            type:String,
            required:true
        },
        place:{
            type:String,
            required:true
        },
        salary:{
            type:String,
            required:true
        }
    })

    const languageProficiency = new mongoose.Schema({
        firstLanguage:{
            type:String,
            required:true
        },
        secondLanguage:{
            type:String,
            required:true
        },
        thirdLanguage:{
            type:String
        }
        })

    const childrenList = new mongoose.Schema({
       name1:{
           type:String
       } ,
       father1:{
           type:String
       },
       birthDate1:{
           type:Date
       },
       name2:{
        type:String
    } ,
    father2:{
        type:String
    },
    birthDate2:{
        type:Date
    },
    name3:{
        type:String
    } ,
    father3:{
        type:String
    },
    birthDate3:{
        type:Date
    }
    })

    const emergencyContact = new mongoose.Schema({
        name:{
            type:String,
            required:true
            },
        fatherName:{
            type:String,
            required:true
        },
        grandFatherName:{
            type:String,
            required:true
        },
        address:{
            type:String,
            required:true
        },
        zone:{
            type:String,
            required:true
        },
        subZone:{
            type:String,
            required:true
        },
        village:{
            type:String,
            required:true
        }
    })
    const staffSchema = new mongoose.Schema({
         SID:{
        type:Number,
        required:true
    },
        staffInformation:staff,
        basicInformation:basic,
        contactInformation:contact,
        highLevelInformation:highLevel,
        workStatusInformation:workStatus,
        specialTrainingInformation:specialTraining,
        workExperienceInformation:workExperience,
        languageProficiencyInformation:languageProficiency,
        childrenListInformation:childrenList,
        emergencyContactInformation:emergencyContact
    })
    const Staff = new mongoose.model("Staff",staffSchema)

    exports.Staff = Staff