const mongoose = require('mongoose')
const { boolean } = require('joi')

const DST = new mongoose.Schema({
    stremptomycin:{
        type:String
    },
    isoniazed:{
        type:String
    },
    rifampcin:{
        type:String
    },
    rthambutol:{
        type:String
    },
    pyrazinamide:{
        type:String
    },
    amikacin:{
        type:String
    },
    capreomycin:{
        type:String
    },
    kanamycin:{
        type:String
    },
    levloxacin:{
        type:String
    },
    ofloxacin:{
        type:String
    }

})

const TBreport = new mongoose.Schema({
    RequestID:{
        type:Number
    },
    PatientUHID:{
        type:Number
    },
    priority:{
        type:String
    },
    department:{
        type:String
    },
    DoctorID:{
        type:Number
    },
    nationalIdNumber:{
        type:String
    },
    status:{
        type:String
    },
    test:{
        type:String
    },
    firstName:{
        type:String
    },sex:{
        type:String
    },
    eritreanID:{
        type:String
    },
    dateOfBirth:{
        type:Date
    },
    address:{
        type:String
    },
    labSerial:{
        type:String
    },
    round:{
        type:String
    },
    facultyName:{
        type:String
    },
    doctorName:{
        type:String
    },
    referralDate:{
        type:Date
    },
    mgitCulture:{
        type:String
    },
    mgitMicroscopy:{
        type:String
    },
    ljCulture:{
        type:String
    },
    geneXpertRapidTest:{
        type:String
    },    
    DST:DST,
    result:{
        type:String
    }
    ,comments:{
        type:String
    },reportedBy:{
        type:String
    },
    recievedBy:{
        type:String
    }
})

const TBReport = new mongoose.model("TBReport",TBreport)
exports.TBReport = TBReport
